// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq_2u8N5HVI2el_RkYcxS4Yb0gBuqRK6U',
    appId: '1:175844833391:web:9ae603b09f8dfcefe6b59a',
    messagingSenderId: '175844833391',
    projectId: 'medica-cc918',
    authDomain: 'medica-cc918.firebaseapp.com',
    storageBucket: 'medica-cc918.appspot.com',
    measurementId: 'G-BGN8DV89PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoAjipBs7_hTEEIXVt_BJjD7lTWL1XUvg',
    appId: '1:175844833391:android:8f6cd810ecc5f8d8e6b59a',
    messagingSenderId: '175844833391',
    projectId: 'medica-cc918',
    storageBucket: 'medica-cc918.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2cS883IiBldEwid6_LxQ9Ppqsczr43a4',
    appId: '1:175844833391:ios:2f2a9accb3996954e6b59a',
    messagingSenderId: '175844833391',
    projectId: 'medica-cc918',
    storageBucket: 'medica-cc918.appspot.com',
    iosClientId: '175844833391-g8ish36oa2qnr4dq2vtlurumoenpbj9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.medica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2cS883IiBldEwid6_LxQ9Ppqsczr43a4',
    appId: '1:175844833391:ios:2f2a9accb3996954e6b59a',
    messagingSenderId: '175844833391',
    projectId: 'medica-cc918',
    storageBucket: 'medica-cc918.appspot.com',
    iosClientId: '175844833391-g8ish36oa2qnr4dq2vtlurumoenpbj9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.medica',
  );
}
